import adm1 as adm
import sys

input_file = sys.argv[1]

def main():
    print("Starting project with parameters:")
    print("\tInput file: {}".format(input_file))
    print("\tRunning python script. The following logs are generated by the python program")
    print("\n")
    not_empty, z = adm.compute_x_or_y(input_file)
    print("")
    print("--------- RESULT ------------------------------------------------------------")
    print("|")
    print("|  Polyhedron is empty: {}".format(not not_empty))
    if not_empty:
        print("|  It contains the point x={}".format(z))
    else:
        print("|  It satisfies y^TA=0 and y^Tb > 0 with point y={}".format(z))
    print("|")
    print("----------------------------------------------------------------------------")
    print("")

if __name__ == "__main__":
    main()
