import adm1 as adm
import sys

input_file = sys.argv[1]
output_file = sys.argv[2]


def main():
    print("Starting H_representation with parameters:")
    print("\tInput file: {}".format(input_file))
    print("\tOutput file: {}".format(output_file))
    print("\tRunning python script. The following logs are generated by the python program")
    print("\n")
    adm.H_representation(input_file,output_file)

if __name__ == "__main__":
    main()
