import adm1 as adm
import sys

polyhedron = sys.argv[1]
matrix = sys.argv[2]
output_file = sys.argv[3]

def main():
    print("Starting Image with parameters:")
    print("\tPolyhedron: {}".format(polyhedron))
    print("\tMatrix: {}".format(matrix))
    print("\tOutput file: {}".format(output_file))
    print("\tRunning python script. The following logs are generated by the python program")
    print("\n")
    adm.image(polyhedron, matrix, output_file)

if __name__ == "__main__":
    main()
