import adm1 as adm
import sys

input_file = sys.argv[1]
k = sys.argv[2]
output_file = sys.argv[3]

def main():
    print("Starting project with parameters:")
    print("\tInput file: {}".format(input_file))
    print("\tk: {}".format(k))
    print("\tOutput file: {}".format(output_file))
    print("\tRunning python script. The following logs are generated by the python program")
    print("\n")
    adm.projection(input_file,k,output_file)

if __name__ == "__main__":
    main()
